apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: http://argocd.example.com:8080
  admin.enabled: "false"
  oidc.config: |
    name: Keycloak
    issuer: http://keycloak.example.com:8080/realms/default
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
