apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-prjcts
resources:
- ../base
patches:
- path: argocd-cmd-params-cm.yaml
- path: argocd-cm.yaml
- path: argocd-secret.yaml
- path: argocd-rbac-cm.yaml
- path: crb-argocd-application-controller.yaml
- path: crb-argocd-applicationset-controller.yaml
- path: crb-argocd-server.yaml
