apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  sso: |
    issuer: http://keycloak.example.com:8080/realms/default
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: http://argo.example.com:2746/oauth2/callback
    scopes:
      - groups
    rbac:
      enabled: true
